### PR TITLE
Add pages for all orgmycology orgs

### PR DESCRIPTION
**Pull request by Nolski**
This additional creates organization pages for every organization mentioned in Org Mycology's Scientific Open Source Software Landscape document and organizes them by the sections detailed in the corresponding venn diagram.

@RichardLitt This is a first shot at importing all of the relevant data from the OrgMycology diagram. There are some inconsistencies in the data in the repository and what is shown on the image, but I think I have roughly 90% of what is shown. I went through and checked all of the descriptions and so-on but a second set of eyes wouldn't hurt either.

### CODE REVIEW

**Comment by RichardLitt** [comment]
@Nolski

**Comment by RichardLitt** [comment]
Ok!

Why is _build in here? Also, did you try running this and see these errors: 

checking consistency... /Users/richard/src/academic-map/organizations/2i2c.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/academic-data-science-alliance.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/alan-turing-institute.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-association-for-the-advancement-of-science.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-astronomical-society.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-chemical-society.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-geophysical-union.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-physical-society.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-psychological-association.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/american-society-for-microbiology.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/apache-software-foundation.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/association-for-computing-machinery.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/astropy.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/bioconductor.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/center-for-scientific-collaboration-and-community-engagement.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/creative-commons.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/ecological-society-of-america.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/electronic-frontier-foundation.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/european-space-agency.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/example.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/free-software-foundation.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/institute-of-electrical-and-electronics-engineers.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/internet-society.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/japan-aerospace-exploration-agency.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/julia-language.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/linux-foundation.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/matplotlib.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/molecular-sciences-software-institute.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/mozilla-foundation.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/national-aeronautics-and-space-administration.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/numfocus.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/numpy.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/open-knowledge-foundation.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/open-life-science.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/openai.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/ospo.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/project-jupyter.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/pyopensci.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/pytorch.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/research-software-alliance.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/research-software-engineers.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/ropensci.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/science-gateways-community-institute.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/scipy.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/software-freedom-conservancy.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/space-telescope-science-insitute.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/stan.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/sustainoss.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/the-carpentries.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/the-turing-way.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/uk-software-sustainability-institute.md: WARNING: document isn't included in any toctree
/Users/richard/src/academic-map/organizations/us-research-software-sustainability-institute.md: WARNING: document isn't included in any toctree

**Comment by RichardLitt** [comment]
Some of these are duplicates. Can you got through the _toc.yml and remove the ones which are? Take a look at this, where I've started this work: https://github.com/sustainers/academic-map/blob/orgmycology/_toc.yml.

**Comment by RichardLitt** [comment]
I normally run a separate commit with build, but I guess it is fine to include it, too. :)

**Comment by Nolski** [comment]
@RichardLitt Regarding the _build folder, I presumed that build was happening on another branch as I didn't notice

> Ok!
> 
> Why is _build in here? Also, did you try running this and see these errors:
> 
> checking consistency... /Users/richard/src/academic-map/organizations/2i2c.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/academic-data-science-alliance.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/alan-turing-institute.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-association-for-the-advancement-of-science.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-astronomical-society.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-chemical-society.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-geophysical-union.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-physical-society.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-psychological-association.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/american-society-for-microbiology.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/apache-software-foundation.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/association-for-computing-machinery.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/astropy.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/bioconductor.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/center-for-scientific-collaboration-and-community-engagement.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/creative-commons.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/ecological-society-of-america.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/electronic-frontier-foundation.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/european-space-agency.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/example.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/free-software-foundation.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/institute-of-electrical-and-electronics-engineers.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/internet-society.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/japan-aerospace-exploration-agency.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/julia-language.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/linux-foundation.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/matplotlib.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/molecular-sciences-software-institute.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/mozilla-foundation.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/national-aeronautics-and-space-administration.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/numfocus.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/numpy.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/open-knowledge-foundation.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/open-life-science.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/openai.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/ospo.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/project-jupyter.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/pyopensci.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/pytorch.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/research-software-alliance.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/research-software-engineers.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/ropensci.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/science-gateways-community-institute.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/scipy.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/software-freedom-conservancy.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/space-telescope-science-insitute.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/stan.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/sustainoss.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/the-carpentries.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/the-turing-way.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/uk-software-sustainability-institute.md: WARNING: document isn't included in any toctree /Users/richard/src/academic-map/organizations/us-research-software-sustainability-institute.md: WARNING: document isn't included in any toctree

@RichardLitt can you explain what command created this output? None of the linting commands seem to output this for me on this branch as far as I can tell.

**Comment by RichardLitt** [comment]
Try running `npm run build` and `npm run lint`. :)

**Comment by RichardLitt** [comment]
Should be good to go at this point. Thank you for bearing with me on this work!

**Pull request merged**
