### PR TITLE
Create trinity-college-dublin.md

### PR DESCRIPTION
**Pull request by claredillon**
New entry for Trinity College Dublin

### CODE REVIEW

**Comment by RichardLitt** [comment]
Yes, this adds it. But there's no content. Do you have that?

**Comment by claredillon** [comment]
This is a work in progress - hold off on emerging for now

**Comment by claredillon** [comment]
PLease merge if you think it looks OK (and I'll do a little dance! :)

**Comment by RichardLitt** [comment]
Merged. :)

**Pull request closed without merging**
